kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["*"] #"apps", "batch" etc
    verbs: ["get","apply","delete","create","patch","watch"]
    resources: ["pods", "deployments"] #, "services"]
